### ISSUE TITLE
Cannot expand a panel added in the same call

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-accordion-flow#61] opened 2020-05-18 16:02 UTC
A new panel added to the accordion cannot be `opened` in the same call.

**Observed behavior**
![observed](https://user-images.githubusercontent.com/11554739/82234254-8c8b9480-9907-11ea-9f78-8e3f1c16775a.gif)

**Expected behavior**
![expected](https://user-images.githubusercontent.com/11554739/82234252-8b5a6780-9907-11ea-9a47-b70b3893bcf0.gif)

**Example**
```
Accordion accordion = new Accordion();
accordion.add("Panel", new Span("Panel"));

add(new Button("Bug", ev -> {
	AccordionPanel panel = accordion.add("Panel", new Span("Content"));
	accordion.open(panel);
}));

add(new Button("Workaround", ev -> {
	AccordionPanel panel = accordion.add("Panel", new Span("Content"));
	accordion.getElement().executeJs("setTimeout(function(){this.opened=$0}.bind(this))",
	accordion.getElement().indexOfChild(panel.getElement()));
}));

add(accordion);
```

**Version**
Vaadin 14.1.28 (vaadin-accordion-flow 2.0.0)

**Comment by web-padawan** [comment] 2020-05-18 16:26
This is by design. We use native `slotchange` event which is asynchronous and is dispatched by the browser in a microtask queue, not immediately after DOM node is inserted.

There is another workaround that should force synchronous DOM distribution:

```
AccordionPanel panel = accordion.add("Panel", new Span("Content"));
accordion.getElement().executeJs("this._observer.flush())",
accordion.open(panel);
```

However, please note that `_observer` API is removed in the next major release of web component (based on LitElement), so this will no longer work when we include that version to Vaadin 18.

Closing as won't fix. Feel free to ask if you have more questions though.

**Closed by web-padawan** 2020-05-18 16:26 UTC
Labels: wontfix
